import React from 'react';
import { getRiskLevel, getRiskLabel } from './PrivacyScore';

export default function PrivacyCertificate({ stats, onClose }) {
  const { originalCount, redactedCount, remainingCount, score, destination, timestamp } = stats;
  const level = getRiskLevel(score);
  const label = getRiskLabel(score);

  const handlePrint = () => window.print();

  const handleDownload = () => {
    const text = [
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '           VEILiq – PRIVACY CERTIFICATE',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '',
      `  Risk Level         : ${label.toUpperCase()}`,
      `  Privacy Score      : ${score}/100`,
      `  PII Detected       : ${originalCount}`,
      `  PII Redacted       : ${redactedCount}`,
      `  Remaining PII      : ${remainingCount}`,
      destination ? `  Share Destination  : ${destination}` : '',
      `  Generated          : ${new Date(timestamp).toLocaleString()}`,
      '',
      '  Status: ' + (level === 'low' ? '✓ SAFE TO SHARE' : level === 'medium' ? '⚠ SHARE WITH CAUTION' : '✕ REVIEW BEFORE SHARING'),
      '',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '  VEILiq – Think Before You Share',
      '  "Know what you\'re revealing before you share."',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
    ].filter(Boolean).join('\n');

    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `privacy-certificate-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="certificate-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="certificate">
        <button className="cert-close" onClick={onClose} aria-label="Close certificate">✕</button>

        <div className="cert-badge">
          {level === 'low' ? '🛡️' : level === 'medium' ? '⚠️' : '🔴'}
        </div>

        <h2 className="cert-title">Privacy Certificate</h2>
        <p className="cert-subtitle">
          VEILiq AI Analysis Report
          {destination && <> &mdash; For <strong>{destination}</strong></>}
        </p>

        <div className="cert-stats">
          <div className="cert-stat">
            <div className="cert-stat-value">{score}</div>
            <div className="cert-stat-label">Privacy Score</div>
          </div>
          <div className="cert-stat">
            <div className="cert-stat-value">{redactedCount}</div>
            <div className="cert-stat-label">PII Removed</div>
          </div>
          <div className="cert-stat">
            <div className="cert-stat-value">{remainingCount}</div>
            <div className="cert-stat-label">Remaining</div>
          </div>
        </div>

        <div className={`cert-level-badge ${level}`}>
          {level === 'low' && <span>✓</span>}
          {level === 'medium' && <span>⚠</span>}
          {level === 'high' && <span>✕</span>}
          {level === 'low' ? 'Safe to Share' : level === 'medium' ? 'Share with Caution' : 'Review Before Sharing'}
        </div>

        <div className="cert-meta">
          Generated by VEILiq &nbsp;·&nbsp;{' '}
          {new Date(timestamp).toLocaleString()}
          <br />
          <em>"Know what you're revealing before you share."</em>
        </div>

        <div className="cert-actions">
          <button className="btn btn-secondary" onClick={handleDownload} id="cert-download-btn">
            ⬇ Download
          </button>
          <button className="btn btn-primary" onClick={handlePrint} id="cert-print-btn">
            🖨 Print
          </button>
          <button className="btn btn-ghost" onClick={onClose} id="cert-close-btn">
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
